/**
 * Email Service utility for Wacky Races notifications.
 * Uses Resend (https://resend.com) for reliable delivery.
 */

export class EmailService {
    private static API_URL = 'https://api.resend.com/emails';
    private static API_KEY = process.env.RESEND_API_KEY;

    /**
     * Sends an email via Resend API (Fetch based to avoid dependency issues)
     */
    static async sendEmail(params: { to: string; subject: string; html: string }) {
        if (!this.API_KEY) {
            console.error('[EMAIL ERROR] RESEND_API_KEY is not set.');
            return { success: false, error: 'API Key missing' };
        }

        try {
            const response = await fetch(this.API_URL, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${this.API_KEY}`
                },
                body: JSON.stringify({
                    from: 'Wacky Races Notifications <notifications@wackyraces.fun>', // Replace with verified domain if possible
                    to: [params.to],
                    subject: params.subject,
                    html: params.html
                })
            });

            const data = await response.json();
            if (!response.ok) {
                console.error('[EMAIL ERROR] API Response:', data);
                return { success: false, error: data.message };
            }

            return { success: true, data };
        } catch (error) {
            console.error('[EMAIL ERROR] fetch failed:', error);
            return { success: false, error: 'Fetch failed' };
        }
    }

    /**
     * Formats a single sign-up notification
     */
    static async notifyNewSignup(recipient: string, signup: { email: string; type: 'WAITLIST' | 'USER'; wallet?: string }) {
        const subject = `🏁 New Sign-up: ${signup.email}`;
        const html = `
            <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                <h2 style="color: #db2777;">New ${signup.type === 'WAITLIST' ? 'Waitlist Entry' : 'Platform User'}</h2>
                <p>A new operator has just entered the races!</p>
                <div style="background: #f9f9f9; padding: 15px; border-radius: 8px; margin-top: 20px;">
                    <p><strong>Email:</strong> ${signup.email}</p>
                    ${signup.wallet ? `<p><strong>Wallet:</strong> <code style="background: #eee; padding: 2px 4px;">${signup.wallet}</code></p>` : ''}
                    <p><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
                </div>
                <p style="margin-top: 30px; font-size: 12px; color: #666;">
                    Wacky Races Administration System
                </p>
            </div>
        `;

        return this.sendEmail({ to: recipient, subject, html });
    }

    /**
     * Formats a daily digest of sign-ups
     */
    static async sendDailyDigest(recipient: string, signups: any[]) {
        const subject = `📅 Daily Sign-up Digest: ${signups.length} new users`;
        const signupRows = signups.map(s => `
            <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${s.email}</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${s.type}</td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;">${new Date(s.created_at).toLocaleTimeString()}</td>
            </tr>
        `).join('');

        const html = `
            <div style="font-family: sans-serif; max-width: 700px; margin: auto; padding: 20px;">
                <h2 style="color: #db2777;">Daily Operations Summary</h2>
                <p>Here is the list of new sign-ups from the last 24 hours.</p>
                
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                    <thead>
                        <tr style="background: #f4f4f4; text-align: left;">
                            <th style="padding: 10px;">Email</th>
                            <th style="padding: 10px;">Source</th>
                            <th style="padding: 10px;">Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${signupRows}
                    </tbody>
                </table>

                <p style="margin-top: 40px; font-size: 12px; color: #999;">
                    Generated by Wacky Races Cron Worker.
                </p>
            </div>
        `;

        return this.sendEmail({ to: recipient, subject, html });
    }
}
